language: python
os: linux
dist: xenial
install: pip install -r requirements/test.txt
script: tox

jobs:
  include:
    - python: 3.8
      env: TOXENV=tests-py38
      dist: xenial
    - python: 3.8
      env: TOXENV=mutations-py38
      dist: xenial
    - python: 3.8
      env: TOXENV=style-py38
      dist: xenial
    - python: 3.8
      env: TOXENV=docs-py38
      dist: xenial