language: python

matrix:
  include:
    - python: 3.8
      env: TOXENV=tests-py37
      dist: xenial
      sudo: true
    - python: 3.8
      env: TOXENV=mutations-py37
      dist: xenial
      sudo: true
    - python: 3.8
      env: TOXENV=style-py37
      dist: xenial
      sudo: true
    - python: 3.8
      env: TOXENV=docs-py37
      dist: xenial
      sudo: true

install:
  - pip install -r requirements/test.txt
script:
  - tox